[settings]
background = "minecraft"

[preferances]
subreddit = "amItheasshole"
ttsengine = "gtts"

[redditlogin]
client_id = "WG3ezIr2eqgmLLyZEFTEKA"
client_secret = "jaUS5N0VkStEm0zBNKGBvZW29ICdEA"
user_agent = "reddit_tts_video_maker"
username = "teamtijmi"
password = "@Thijmen18"

[tiktok]
tiktok_session_id = false
