[settings]
background = ""

[preferances]
subreddit = ""
ttsengine = ""

[redditlogin]
client_id = ""
client_secret = ""
user_agent = "teamtijmi"
username = ""
password = "

[tiktok]
tiktok_session_id = false
