[settings]
background = "woodworking"

[preferances]
subreddit = "AmItheasshole"
ttsengine = "pyttsx3"

[redditlogin]
client_id = "D_CzpEhTMVe8AUpbPuNIsA"
client_secret = "79nIVU5O17hi9QOJ-lol1yjFsGMqhA"
user_agent = "teamtijmi"
username = "teamtijmi"
password = "@Thijmen18"

[tiktok]
tiktok_session_id = false
