[settings]
background = false

[preferances]
subreddit = false
ttsengine = false

[redditlogin]
client_id =false
client_secret = false
user_agent = "reddit_tts_video_maker"
username = false
password = false

[tiktok]
tiktok_session_id = false
