[settings]
firsttime = "yes"

[preferances]
subreddit = "tifu"
voice = "streamlabspolly"

[redditlogin]
client_id="WG3ezIr2eqgmLLyZEFTEKA"
client_secret="jaUS5N0VkStEm0zBNKGBvZW29ICdEA"
user_agent="test"
username="teamtijmi"
password="@Thijmen18"

[tiktok]
session_id = "e6647ac779d54b8ef21df9a2ead5340e"
